language: java
sudo: false
install: true

os: linux
dist: xenial

addons:
  sonarcloud:
    organization: "lequal"

jdk:
  - openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

notifications:
  email: false

deploy:
  provider: releases
  token: "$GITHUB_TOKEN"
  file_glob: true
  file: "target/sonar-hadolint-plugin-*.jar"
  skip_cleanup: true
  name: "Sonar Hadolint Plugin version $TRAVIS_TAG"
  draft: true
  on:
    branch: master
    tags: true
    jdk: openjdk11